const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('browserAPI', {
  createTab: (url) => ipcRenderer.invoke('tab-create', url),
  closeTab: (id) => ipcRenderer.invoke('tab-close', id),
  activateTab: (id) => ipcRenderer.invoke('tab-activate', id),
  selectTab: (id, selected) => ipcRenderer.invoke('tab-select', id, selected),
  selectAllTabs: (selected) => ipcRenderer.invoke('tab-select-all', selected),
  setMosaic: (enabled) => ipcRenderer.invoke('set-mosaic', enabled),
  setSidePanel: (enabled) => ipcRenderer.invoke('set-side-panel', enabled),
  setUiOverlay: (enabled) => ipcRenderer.invoke('set-ui-overlay', enabled),
  navigate: (value) => ipcRenderer.invoke('navigate', value),
  browserAction: (action) => ipcRenderer.invoke('browser-action', action),
  keyboardShortcut: (action) => ipcRenderer.invoke('keyboard-shortcut', action),
  getState: () => ipcRenderer.invoke('get-browser-state'),
  toggleBookmark: () => ipcRenderer.invoke('toggle-bookmark'),
  clearCookies: (mode) => ipcRenderer.invoke('clear-cookies', mode),
  getExtensions: () => ipcRenderer.invoke('get-extensions'),
  installExtension: () => ipcRenderer.invoke('install-extension'),
  setExtensionEnabled: (id, enabled) => ipcRenderer.invoke('set-extension-enabled', id, enabled),
  openExtensionOptions: (id) => ipcRenderer.invoke('open-extension-options', id),
  manageExtensions: () => ipcRenderer.invoke('manage-extensions'),
  openWebStore: () => ipcRenderer.invoke('open-webstore'),
  openProfile: () => ipcRenderer.invoke('open-profile'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  onTabsUpdated: (callback) => ipcRenderer.on('tabs-updated', (_event, data) => callback(data)),
  onLoadingChanged: (callback) => ipcRenderer.on('loading-changed', (_event, data) => callback(data)),
  onFocusAddress: (callback) => ipcRenderer.on('focus-address', callback),
  onBookmarksUpdated: (callback) => ipcRenderer.on('bookmarks-updated', (_event, data) => callback(data)),
  onDownloadStarted: (callback) => ipcRenderer.on('download-started', (_event, data) => callback(data)),
  onDownloadFinished: (callback) => ipcRenderer.on('download-finished', (_event, data) => callback(data)),
  onBrowserToast: (callback) => ipcRenderer.on('browser-toast', (_event, message) => callback(message)),
  onKeyboardAction: (callback) => ipcRenderer.on('keyboard-action', (_event, action) => callback(action))
});
